permalink:           /:title
relative_permalinks: true

highlighter:         pygments
markdown:            kramdown
kramdown:
  enable_coderay:    false

title:               Ivan Smirnov
tagline:             on all things tech and then some
description:         on all things tech and then some
url:                 http://ivansmirnov.io
paginate:            1
min_related_tags:    2
excerpt_separator:   <!--more-->

safe:                true
lsi:                 false

sass:
  sass_dir:          _sass
  style:             compressed

author:
  name:              Ivan Smirnov
  url:               http://ivansmirnov.io
  email:             i.s.smirnov@gmail.com

social:
  github:            aldanor
  twitter:           aldanor
  linkedin:          ivsmirnov

apps:
    facebook:        928520860520689
    disqus:          aldanor
    ga:              UA-65579615-1
