permalink:           pretty
relative_permalinks: true

highlighter:         pygments
markdown:            redcarpet

title:               Ivan Smirnov
tagline:             all things tech
description:         Ivan Smirnov's Personal Blog
url:                 http://ivansmirnov.io
paginate:            1
min_related_tags:    2

sass:
  sass_dir:          public/css
  style:             compressed

author:
  name:              Ivan Smirnov
  url:               http://ivansmirnov.io
  email:             i.s.smirnov@gmail.com

social:
  github:            aldanor
  twitter:           aldanor
  facebook:          i.s.smirnov
  linkedin:          ivsmirnov

apps:
    facebook:        928520860520689
    disqus:          aldanor
    ga:              UA-65579615-1
