permalink:           pretty
relative_permalinks: true

highlighter:         pygments
markdown:            redcarpet

title:               Ivan Smirnov
tagline:             on all things tech
url:                 http://aldanor.github.io
paginate:            1
baseurl:             ""

sass:
  sass_dir:          _sass
  style:            :compressed

author:
  name:              Ivan Smirnov
  url:               https://twitter.com/aldanor
  email:             i.s.smirnov@gmail.com

version:             2.0.0
github:
  repo:              https://github.com/aldanor/aldanor.github.io
