permalink:           pretty
relative_permalinks: true

highlighter:         pygments
markdown:            redcarpet

title:               Ivan Smirnov
tagline:             on all things tech
url:                 http://ivansmirnov.io
paginate:            1

sass:
  sass_dir:          _sass
  style:            :compressed

author:
  name:              Ivan Smirnov
  url:               https://twitter.com/aldanor
  email:             i.s.smirnov@gmail.com

social:
  github:            aldanor
  twitter:           aldanor
  facebook:          i.s.smirnov
  linkedin:          ivsmirnov

apps:
    disqus:          aldanor
    ga:              UA-65579615-1
